remote_theme: pages-themes/Time machine@v0.2.0
plugins:
  - jekyll-remote-theme
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - index.md
title: GR
description: The purpose of this website is to provide a demo website for students.