remote_theme: pages-themes/leap-day@v0.2.0
plugins:
  - jekyll-remote-theme
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - index.md
title: GROUP_3
description: Welcome to our Final Project Portal, where we showcase our innovative solution that integrates data-driven workflows with practical applications. 
  